---
runtime: go113
env: standard
instance_class: F1
automatic_scaling:
  target_cpu_utilization: 0.85
  min_instances: 1
  max_instances: 3
  min_pending_latency: 30ms  # default value
  max_pending_latency: automatic
  max_concurrent_requests: 50

# basic_scaling:
#   max_instances: 3
# Trick #1
# manual_scaling:
#   instances: 1

# Trick #2 - downgrade default resources
resources:
  # cpu: 1
  # memory_gb: 0.6
  # disk_size_gb: 10
# Trick #3
# gcloud app deploy --version dev
# when done testing SWITCH OFF
# gcloud app versions stop dev
# and SWITCH ON
# gcloud app versions start dev

handlers:
  - url: /.*
    script: auto
    secure: always

# All URLs ending in .gif .png or .jpg are treated as paths to
# static files in the static/ directory. The URL pattern is a
# regular expression, with a grouping that is inserted into the
# path to the file.
  - url: /(.*\.(gif|png|jpg))$
    static_files: static/\1
    upload: static/.*\.(gif|png|jpg)$
    secure: always
    expiration: "30d"


includes:
  - .env.yaml
