---
runtime: go113
env: standard

# Trick #1
manual_scaling:
  instances: 1
# Trick #2 - downgrade default resources
resources:
  # cpu: 1
  # memory_gb: 0.6
  # disk_size_gb: 10
# Trick #3
# gcloud app deploy --version dev
# when done testing SWITCH OFF
# gcloud app versions stop dev
# and SWITCH ON
# gcloud app versions start dev

handlers:
  - url: /.*
    script: auto

includes:
  - .env.yaml
